#!/bin/sh

[ -f config.sh ] || { echo "Unable to find config.sh"; exit 1; }
. ./config.sh

echo -n "WARNING: Cleaning out everything, proceed? (yes/no) "
read yn

if [ "$yn" != "yes" ]; then
    exit 1
fi

if [ -e Makefile ]; then
    echo "making maintainer-clean..."
    make maintainer-clean 2>&1 > /dev/null
fi

echo "cleaning out Makefile.in's..."
find . -name "Makefile.in" -exec rm {} \;

echo "cleaning out backups..."
find . -name '*~' -exec rm {} \;

echo "cleaning out symlinks..."
find . -type l -not -name README -exec rm {} \;

echo "cleaning out other..."
rm -rf autom4te.cache
rm -f aclocal.m4 defs.h.in configure config.log config.status

echo -n "Make a tarball? (y/n) "
read yn

if [ "$yn" = "y" ]; then
    DIR="`pwd`"
    cd ..
    rm -f "$AUTO_PROJECT.tar.gz"
    tar cvf "$AUTO_PROJECT.tar" "$DIR"
    gzip -9 "$AUTO_PROJECT.tar"
    cd $DIR
fi
