on: [push, pull_request]

name: Build

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Ubuntu-20.04
        run: |
          docker build -f Docker/Test-Build-Ubuntu-20.04.docker .
      - name: Build Archlinux
        run: |
          docker build -f Docker/Test-Build-Archlinux.docker .
  build-macos-10_15:
    name: Build macOS 10.15
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build macOS 10.15
        run: |
          mkdir build
          cd build
          export PATH="$(brew --prefix llvm)/bin:$PATH"
          cmake -DTOOLCHAIN=gcc -DBUILD_CONFIG=Release ..
          make
          ./bin/c2ffi --help
